version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: inventory

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: