# App deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: docker.io/itsdaveba/python-docker:latest
        env:
        - name: MYSQL_HOST
          value: localhost
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: secret
        - name: MYSQL_DB
          value: inventory
      - name: centos
        image: centos:7
        command:
          - "bin/bash"
          - "-c"
          - "sleep 10000"
---
# Database deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql
  template:
    metadata:
      labels:
        db: mysql
    spec:
      containers:
      - name: mysqldb
        image: docker.io/mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
      - name: centos
        image: centos:7
        command:
          - "bin/bash"
          - "-c"
          - "sleep 10000"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: myapp
  type: NodePort