apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: docker.io/itsdaveba/python-docker:latest
        env:
        - name: MYSQL_HOST
          value: localhost
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: secret
        - name: MYSQL_DB
          value: inventory
      - name: mysqldb
        image: docker.io/mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
          - name: mysql-config
            mountPath: /etc/mysql
      - name: centos
        image: centos:7
        command:
          - "bin/bash"
          - "-c"
          - "sleep 10000"
        volumeMounts:
          - name: mysql
            mountPath: /tmp/mysql
          - name: mysql-config
            mountPath: /tmp/mysql-config
      volumes:
      - name: mysql
        emptyDir: {}
      - name: mysql-config
        emptyDir: {}
---