apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: itsdaveba/python-docker:latest
      - name: mysqldb
        image: mysql:5.7
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: myapp