apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: itsdaveba/python-docker:latest
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "mysqldb"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "secret"
        - name: MYSQL_DB
          value: "inventory"
      - name: mysqldb
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "secret"
      - name: centos
        image: centos:7
        command:
          - "bin/bash"
          - "-c"
          - "sleep 10000"